project: 
  type: website
  output-dir: docs

website:
  title: "Marco Reina Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/starter-analysis-exercise.qmd
    right:
      - icon: github 
        href: https://reinaantillon.github.io/marcoreina-portafolio/
format:
  html:
    theme: cerulean
    highlight: zenburn
    css: styles.css
    toc: FALSE